### ISSUE TITLE
Feature request for the component as InputTags but option list as multiselect dropdown

### ISSUE THREAD

**Issue by dimuch** [ironSource/fusion-ui#12]
# 🚀 feature request

### Relevant Package

 This feature request is for @ironsource/fusion-ui@5.4.0

### Blocker
- [x] Yes
- [ ] No

### Description
 A clear and concise description of the problem or missing capability...
Please provide the Component as in the screenshot. Generally, it has to be an input field with a placeholder if no selected values,
the list with options which has to be opened/closed on mouse click(on enter press if Component with focus). 
If autocomplete option has TRUE value there has to be the possibility to provide custom logic to make filtering within options or make API requests to the server.
The option of the list has to be with a checkbox and value.
If the user selects an option(click on the row with needed value/press space btn) selected option has to be highlighted(must to be customized: to set needed styles).
Under options list located controls buttons: Ok, Cancel, Clear selection. All captions have to be customizable and with the option to apply position(left/right) on purpose.
When the user clicks Ok -- all selected options became tags and values should be visible in the top input area with the option to delete(x button).
When the user clicks Cancel -- input has to have values that were selected before changes.
When the user clicks Clear selection all selected values became deselected.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### 🌍  Your environment you work with
 React
<img width="564" alt="Screenshot 2022-01-21 at 20 11 07" src="https://user-images.githubusercontent.com/7248180/150578581-3b68181a-c54a-43c4-8634-700f01cb0ebd.png">

Please update regarding possible ETA of component development

**Comment by AndyKIron** [comment]
Added in  1.1.0-rc.x
