### ISSUE TITLE
Dropdown include-exclude component search input must be focused on drop options

### ISSUE THREAD

**Issue by moranamar** [ironSource/fusion-ui#186]
Please add search focus filed by default on open dropdown menu
![image](https://user-images.githubusercontent.com/42141491/233930117-a39211a0-a030-444b-8204-4cc447b30264.png)

**Comment by AndyKIron** [comment]
@moranamar got this test. Let's check

**Comment by AndyKIron** [comment]
@moranamar It done. You can check in on this story:
https://fusion-storybook.ironsrc.mobi/branch_release-5.x.x/iframe.html?args=&id=components-dropdown-include-exclude--default&viewMode=story
